spring.application.name=networkhealthmonitor
server.port=8085


spring.data.arangodb.host=127.0.0.1
spring.data.arangodb.port=8529
spring.data.arangodb.database=netmon
spring.data.arangodb.user=root
spring.data.arangodb.password=root

device.inactive.threshold.minutes=5

#spring.datasource.url=jdbc:mysql://localhost:3307/network_db
#spring.datasource.username=root
#spring.datasource.password=root

